apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jr3s8i83n-python 
  janus-idp.io/tekton: jr3s8i83n-python
  backstage.io/kubernetes-id: jr3s8i83n-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jr3s8i83n-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml