apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jr3s8i83n-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jr3s8i83n-python 
  name: jr3s8i83n-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jr3s8i83n-python 
